name: Terraform Prerequisites

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Install AWS CLI v2 (official installer)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Create S3 bucket for Terraform state (ignore if exists)
        run: |
          aws s3api create-bucket --bucket terraform-module-infra-state --region $AWS_DEFAULT_REGION || echo "Bucket may already exist."

      - name: Enable bucket encryption (ignore if already set)
        run: |
          aws s3api put-bucket-encryption --bucket terraform-module-infra-state --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}' || echo "Encryption may already be enabled."

      - name: Create DynamoDB table for state locking (ignore if exists)
        run: |
          aws dynamodb create-table \
            --table-name terraform-locks \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST \
            --region $AWS_DEFAULT_REGION || echo "Table may already exist."

      - name: Confirm backend resources
        run: |
          aws s3api head-bucket --bucket terraform-module-infra-state
          aws dynamodb describe-table --table-name terraform-locks
